"""Q16 kernel2 sleep / consolidation boundary for HTCE-Origin Clean Body.

This module implements offline replay and rule-candidate promotion.  It does
not mutate the runtime L2/L3 state because L1/L2/L3 body body commit has not been
integrated yet.  Consolidation returns explicit reports containing promoted
rule candidates, blocked contradictions, replay provenance, and no-regression
status.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Iterable, Mapping, Sequence

from htce_origin.kernel.core import EntityId, FactFrame, RelationId
from htce_origin.kernel.q16 import (
    COS_SCALE,
    DEFAULT_MODULUS,
    q_add,
    q_cos_lut,
    q_delta,
    q_mod,
    q_sin_lut,
    q_toroidal_loss_lut,
    q_toroidal_loss_vector,
    q_vector,
)
from htce_origin.governance.proof import Judgment, Statement, TheoremLayer


class LearningError(ValueError):
    """Raised when sleep/consolidation input is malformed."""


class EpisodeFactStatus(str, Enum):
    ACTIVE = "active"
    SUPERSEDED = "superseded"
    QUARANTINED = "quarantined"


class RuleStatus(str, Enum):
    PROMOTED = "promoted"
    BLOCKED = "blocked"
    CANDIDATE = "candidate"


@dataclass(frozen=True)
class EpisodeFact:
    """Traceable fact observed in L2 replay material.

    ``negated=True`` represents an explicit correction/refutation candidate.
    It is not deleted.  It is retained in the trace index and can block rule
    promotion during sleep.
    """

    fact: FactFrame
    trace_id: str
    step_index: int = 0
    negated: bool = False
    status: EpisodeFactStatus = EpisodeFactStatus.ACTIVE

    def __post_init__(self) -> None:
        if not self.trace_id:
            raise LearningError("trace_id must be non-empty")
        if int(self.step_index) < 0:
            raise LearningError("step_index must be non-negative")

    @property
    def signature(self) -> str:
        marker = "NOT" if self.negated else "POS"
        return f"{marker}:{self.fact.subject.value}:{self.fact.relation.value}:{self.fact.object.value}"

    @property
    def positive_signature(self) -> str:
        return f"POS:{self.fact.subject.value}:{self.fact.relation.value}:{self.fact.object.value}"

    @property
    def contradiction_signature(self) -> str:
        return f"NOT:{self.fact.subject.value}:{self.fact.relation.value}:{self.fact.object.value}"

    def statement(self) -> Statement:
        st = Statement.atom(self.fact.relation.value, self.fact.subject.value, self.fact.object.value)
        return st.negate() if self.negated else st


@dataclass(frozen=True)
class EpisodeRecord:
    episode_id: str
    facts: tuple[EpisodeFact, ...]
    source: str = "sleep_replay"

    def __post_init__(self) -> None:
        if not self.episode_id:
            raise LearningError("episode_id must be non-empty")
        object.__setattr__(self, "facts", tuple(self.facts))
        if not self.facts:
            raise LearningError("episode must contain at least one fact")


@dataclass(frozen=True)
class RuleCandidate:
    """Candidate L3 rule generated by sleep compression.

    A promoted rule is still a rule candidate, not a direct answer.  It must be
    checked by proof/evidence/policy gates before it can affect user-visible
    output.
    """

    statement: Statement
    support_count: int
    trace_ids: tuple[str, ...]
    status: RuleStatus
    reason: str
    rule_id: str = field(default="")

    def __post_init__(self) -> None:
        object.__setattr__(self, "trace_ids", tuple(self.trace_ids))
        if int(self.support_count) < 0:
            raise LearningError("support_count must be non-negative")
        if not self.rule_id:
            digest = hashlib.sha256()
            digest.update(self.statement.canonical().encode("utf-8"))
            digest.update(str(self.support_count).encode("ascii"))
            digest.update(self.status.value.encode("ascii"))
            for trace_id in self.trace_ids:
                digest.update(b"|")
                digest.update(trace_id.encode("utf-8"))
            object.__setattr__(self, "rule_id", digest.hexdigest())


@dataclass(frozen=True)
class NoRegressionProbe:
    query: str
    expected_answer: str

    def __post_init__(self) -> None:
        if not self.query or not self.expected_answer:
            raise LearningError("no-regression probes require query and expected_answer")


@dataclass(frozen=True)
class ConsolidationReport:
    replayed_episodes: int
    replayed_facts: int
    promoted_rules: tuple[RuleCandidate, ...]
    blocked_rules: tuple[RuleCandidate, ...]
    trace_index: Mapping[str, tuple[str, ...]]
    old_fact_signatures: tuple[str, ...]
    no_regression_passed: bool
    regression_failures: tuple[str, ...]

    @property
    def promoted_count(self) -> int:
        return len(self.promoted_rules)

    @property
    def blocked_count(self) -> int:
        return len(self.blocked_rules)


class SleepConsolidator:
    """Offline sleep/replay consolidator.

    The consolidator stores replayable episode material and emits L3 rule
    candidates.  It never deletes episode facts and never mutates runtime L2/L3
    state directly.
    """

    def __init__(self, *, min_support: int = 2) -> None:
        if int(min_support) <= 0:
            raise LearningError("min_support must be positive")
        self.min_support = int(min_support)
        self._episodes: list[EpisodeRecord] = []
        self._last_report: ConsolidationReport | None = None

    @property
    def episodes(self) -> tuple[EpisodeRecord, ...]:
        return tuple(self._episodes)

    @property
    def last_report(self) -> ConsolidationReport | None:
        return self._last_report

    def record_episode(self, episode: EpisodeRecord) -> EpisodeRecord:
        self._episodes.append(episode)
        return episode

    def replay(self) -> tuple[EpisodeRecord, ...]:
        return tuple(self._episodes)

    def trace_index(self) -> dict[str, tuple[str, ...]]:
        acc: dict[str, list[str]] = {}
        for episode in self._episodes:
            for fact in episode.facts:
                acc.setdefault(fact.signature, []).append(fact.trace_id)
        return {key: tuple(values) for key, values in sorted(acc.items())}

    def lookup_latest_fact(self, subject: EntityId | str, relation: RelationId | str) -> EpisodeFact | None:
        subject_id = subject.value if isinstance(subject, EntityId) else EntityId(subject).value
        relation_id = relation.value if isinstance(relation, RelationId) else RelationId(relation).value
        latest: EpisodeFact | None = None
        for episode in self._episodes:
            for fact in episode.facts:
                if fact.negated or fact.status == EpisodeFactStatus.QUARANTINED:
                    continue
                if fact.fact.subject.value == subject_id and fact.fact.relation.value == relation_id:
                    if latest is None or fact.step_index >= latest.step_index:
                        latest = fact
        return latest

    def consolidate(
        self,
        *,
        theorem_layer: TheoremLayer | None = None,
        probes: Sequence[NoRegressionProbe] = (),
        answerer: Callable[[str], str] | None = None,
    ) -> ConsolidationReport:
        trace_index = self.trace_index()
        positive: dict[str, list[EpisodeFact]] = {}
        negative: dict[str, list[EpisodeFact]] = {}
        replayed_facts = 0

        for episode in self._episodes:
            for fact in episode.facts:
                replayed_facts += 1
                if fact.negated:
                    negative.setdefault(fact.positive_signature, []).append(fact)
                else:
                    positive.setdefault(fact.positive_signature, []).append(fact)

        promoted: list[RuleCandidate] = []
        blocked: list[RuleCandidate] = []

        for signature, facts in sorted(positive.items()):
            first = facts[0]
            trace_ids = tuple(f.trace_id for f in facts)
            statement = first.statement()
            if signature in negative:
                all_traces = trace_ids + tuple(f.trace_id for f in negative[signature])
                blocked.append(RuleCandidate(
                    statement=statement,
                    support_count=len(facts),
                    trace_ids=all_traces,
                    status=RuleStatus.BLOCKED,
                    reason="contradiction quarantine: positive and negated replay facts coexist",
                ))
                continue
            if len(facts) >= self.min_support:
                candidate = RuleCandidate(
                    statement=statement,
                    support_count=len(facts),
                    trace_ids=trace_ids,
                    status=RuleStatus.PROMOTED,
                    reason="repeated episode support reached promotion threshold",
                )
                promoted.append(candidate)
                if theorem_layer is not None:
                    theorem_layer.add_judgment(Judgment(statement, evidence_id=trace_ids[-1], source="derived", supported=True))

        for signature, facts in sorted(negative.items()):
            if signature not in positive:
                first = facts[0]
                blocked.append(RuleCandidate(
                    statement=first.statement(),
                    support_count=0,
                    trace_ids=tuple(f.trace_id for f in facts),
                    status=RuleStatus.BLOCKED,
                    reason="negative-only replay material is retained but not promoted",
                ))

        failures = self._run_no_regression(probes, answerer)
        report = ConsolidationReport(
            replayed_episodes=len(self._episodes),
            replayed_facts=replayed_facts,
            promoted_rules=tuple(promoted),
            blocked_rules=tuple(blocked),
            trace_index=trace_index,
            old_fact_signatures=tuple(trace_index.keys()),
            no_regression_passed=not failures,
            regression_failures=tuple(failures),
        )
        self._last_report = report
        return report

    def _run_no_regression(
        self,
        probes: Sequence[NoRegressionProbe],
        answerer: Callable[[str], str] | None,
    ) -> list[str]:
        failures: list[str] = []
        if not probes:
            return failures
        if answerer is None:
            raise LearningError("answerer is required when no-regression probes are supplied")
        for probe in probes:
            observed = answerer(probe.query)
            if observed != probe.expected_answer:
                failures.append(f"{probe.query}: expected {probe.expected_answer!r}, got {observed!r}")
        return failures


@dataclass(frozen=True)
class ToroidalSleepCompressionReport:
    """Integer-only report for L2 -> L3 toroidal sleep compression.

    The report is an offline learning artifact.  It records only Q16 phases,
    integer losses, counters and deterministic diagnostics.  It does not commit
    a rule into runtime memory and it does not authorize a user-visible answer.
    """

    sample_count: int
    epochs: int
    l2_dimension: int
    l3_dimension: int
    l3_state_q16: tuple[int, ...]
    initial_reconstruction_loss: int
    final_reconstruction_loss: int
    sparsity_penalty: int
    total_loss: int
    accepted_updates: int
    loss_improved: bool
    rule_authorized: bool = False
    reason: str = "toroidal sleep compression is offline and non-authoritative"

    def __post_init__(self) -> None:
        if self.sample_count <= 0:
            raise LearningError("sample_count must be positive")
        if self.epochs <= 0:
            raise LearningError("epochs must be positive")
        if self.l2_dimension <= 0 or self.l3_dimension <= 0:
            raise LearningError("dimensions must be positive")
        object.__setattr__(self, "l3_state_q16", tuple(int(v) for v in self.l3_state_q16))
        if self.rule_authorized:
            raise LearningError("toroidal sleep report cannot authorize rules or answers")


class ToroidalSleepConsolidator:
    """Integer-only toroidal compression of L2 trajectories into an L3 state.

    This is the strict HTCE sleep path:

    residual_i = end_i - start_i mod N
    target_L3 = Compress(residual_i)
    L3 <- L3 + eta * signed_delta_N(L3, target_L3) mod N
    prediction = start_i + Expand(L3) mod N

    The loss is the LUT-backed toroidal loss already used by the Q16 kernel,
    plus an integer sparsity penalty that keeps the semantic L3 channel close
    to sparse torus anchors.  No PyTorch, NumPy, trigonometric runtime calls or
    floating-point constants are used.
    """

    def __init__(
        self,
        *,
        dim_l2: int,
        dim_l3: int,
        sparsity_lambda_bp: int = 500,
        learning_rate_bp: int = 1000,
        modulus: int = DEFAULT_MODULUS,
        initial_l3_state: Iterable[int] | None = None,
    ) -> None:
        if int(dim_l2) <= 0 or int(dim_l3) <= 0:
            raise LearningError("dim_l2 and dim_l3 must be positive")
        if int(modulus) <= 1:
            raise LearningError("modulus must be greater than one")
        if not 0 <= int(sparsity_lambda_bp) <= 10000:
            raise LearningError("sparsity_lambda_bp must be in [0, 10000]")
        if not 0 <= int(learning_rate_bp) <= 10000:
            raise LearningError("learning_rate_bp must be in [0, 10000]")
        self.dim_l2 = int(dim_l2)
        self.dim_l3 = int(dim_l3)
        self.sparsity_lambda_bp = int(sparsity_lambda_bp)
        self.learning_rate_bp = int(learning_rate_bp)
        self.modulus = int(modulus)
        if initial_l3_state is None:
            self.l3_state_q16 = tuple(0 for _ in range(self.dim_l3))
        else:
            self.l3_state_q16 = self._require_vector(initial_l3_state, self.dim_l3, "initial_l3_state")

    def _require_vector(self, values: Iterable[int], dimension: int, name: str) -> tuple[int, ...]:
        vector = q_vector(values, self.modulus)
        if len(vector) != dimension:
            raise LearningError(f"{name} dimension mismatch")
        return vector

    def _require_batch(self, values: Iterable[Iterable[int]], dimension: int, name: str) -> tuple[tuple[int, ...], ...]:
        batch = tuple(self._require_vector(item, dimension, name) for item in values)
        if not batch:
            raise LearningError(f"{name} must contain at least one vector")
        return batch

    def _signed_delta(self, source: int, target: int) -> int:
        forward = (int(target) - int(source)) % self.modulus
        half = self.modulus // 2
        if forward <= half:
            return forward
        return forward - self.modulus

    def _step_toward(self, source: int, target: int) -> int:
        delta = self._signed_delta(source, target)
        step = (delta * self.learning_rate_bp) // 10000
        if step == 0 and delta != 0 and self.learning_rate_bp > 0:
            step = 1 if delta > 0 else -1
        return q_add(source, step, self.modulus)

    def _compress_residual_to_l3(self, residual: tuple[int, ...]) -> tuple[int, ...]:
        buckets: list[list[int]] = [[] for _ in range(self.dim_l3)]
        for index, phase in enumerate(residual):
            buckets[index % self.dim_l3].append(phase)
        compressed: list[int] = []
        for bucket in buckets:
            if not bucket:
                compressed.append(0)
                continue
            anchor = bucket[0]
            signed_sum = 0
            for phase in bucket:
                signed_sum += self._signed_delta(anchor, phase)
            compressed.append(q_add(anchor, signed_sum // len(bucket), self.modulus))
        return tuple(compressed)

    def _expand_l3_to_l2(self, l3_state: tuple[int, ...] | None = None) -> tuple[int, ...]:
        source = self.l3_state_q16 if l3_state is None else self._require_vector(l3_state, self.dim_l3, "l3_state")
        return tuple(source[index % self.dim_l3] for index in range(self.dim_l2))

    def _trajectory_residual(self, start: tuple[int, ...], end: tuple[int, ...]) -> tuple[int, ...]:
        return tuple(q_mod(e - s, self.modulus) for s, e in zip(start, end))

    def _predict_end(self, start: tuple[int, ...], l3_state: tuple[int, ...] | None = None) -> tuple[int, ...]:
        expanded = self._expand_l3_to_l2(l3_state)
        return tuple(q_add(s, delta, self.modulus) for s, delta in zip(start, expanded))

    def reconstruction_loss(self, starts_q16: Iterable[Iterable[int]], ends_q16: Iterable[Iterable[int]]) -> int:
        starts = self._require_batch(starts_q16, self.dim_l2, "starts_q16")
        ends = self._require_batch(ends_q16, self.dim_l2, "ends_q16")
        if len(starts) != len(ends):
            raise LearningError("starts_q16 and ends_q16 must have the same sample count")
        total = 0
        for start, end in zip(starts, ends):
            total += q_toroidal_loss_vector(self._predict_end(start), end, self.modulus)
        return total // len(starts)

    def sparsity_penalty(self, l3_state: tuple[int, ...] | None = None) -> int:
        source = self.l3_state_q16 if l3_state is None else self._require_vector(l3_state, self.dim_l3, "l3_state")
        base = sum(q_toroidal_loss_lut(value, self.modulus) for value in source) // len(source)
        return (base * self.sparsity_lambda_bp) // 10000

    def total_loss(self, starts_q16: Iterable[Iterable[int]], ends_q16: Iterable[Iterable[int]]) -> int:
        return self.reconstruction_loss(starts_q16, ends_q16) + self.sparsity_penalty()

    def consolidate_offline(
        self,
        l2_starts_q16: Iterable[Iterable[int]],
        l2_ends_q16: Iterable[Iterable[int]],
        *,
        epochs: int = 4,
    ) -> ToroidalSleepCompressionReport:
        if int(epochs) <= 0:
            raise LearningError("epochs must be positive")
        starts = self._require_batch(l2_starts_q16, self.dim_l2, "l2_starts_q16")
        ends = self._require_batch(l2_ends_q16, self.dim_l2, "l2_ends_q16")
        if len(starts) != len(ends):
            raise LearningError("l2_starts_q16 and l2_ends_q16 must have the same sample count")

        initial_loss = self.reconstruction_loss(starts, ends)
        accepted_updates = 0
        for _epoch in range(int(epochs)):
            for start, end in zip(starts, ends):
                residual = self._trajectory_residual(start, end)
                target_l3 = self._compress_residual_to_l3(residual)
                before_state = self.l3_state_q16
                before_loss = self.reconstruction_loss(starts, ends) + self.sparsity_penalty(before_state)
                candidate_state = tuple(self._step_toward(src, tgt) for src, tgt in zip(before_state, target_l3))
                after_recon = 0
                for batch_start, batch_end in zip(starts, ends):
                    after_recon += q_toroidal_loss_vector(self._predict_end(batch_start, candidate_state), batch_end, self.modulus)
                after_recon //= len(starts)
                after_loss = after_recon + self.sparsity_penalty(candidate_state)
                if after_loss <= before_loss:
                    self.l3_state_q16 = candidate_state
                    accepted_updates += 1

        final_loss = self.reconstruction_loss(starts, ends)
        penalty = self.sparsity_penalty()
        return ToroidalSleepCompressionReport(
            sample_count=len(starts),
            epochs=int(epochs),
            l2_dimension=self.dim_l2,
            l3_dimension=self.dim_l3,
            l3_state_q16=self.l3_state_q16,
            initial_reconstruction_loss=initial_loss,
            final_reconstruction_loss=final_loss,
            sparsity_penalty=penalty,
            total_loss=final_loss + penalty,
            accepted_updates=accepted_updates,
            loss_improved=final_loss <= initial_loss,
        )

    def export_l3_semantic_state(self) -> L3SemanticState:
        """Export the consolidated L3 attractor as a runtime-ready Q256 state."""
        return L3SemanticState(self.l3_state_q16, self.modulus)

    def derive_l3_coupling_matrix(
        self,
        l2_starts_q16: Iterable[Iterable[int]],
        l2_ends_q16: Iterable[Iterable[int]],
    ) -> L3CouplingMatrix:
        """Derive a deterministic Q15 coupling matrix from replay trajectories.

        Each trajectory residual is compressed into L3.  Pairwise phase coherence
        is measured with the existing integer cosine LUT and averaged.  Positive
        weights synchronize stable rule phases; negative weights repel incoherent
        phases.  The diagonal is kept zero.
        """
        starts = self._require_batch(l2_starts_q16, self.dim_l2, "l2_starts_q16")
        ends = self._require_batch(l2_ends_q16, self.dim_l2, "l2_ends_q16")
        if len(starts) != len(ends):
            raise LearningError("l2_starts_q16 and l2_ends_q16 must have the same sample count")
        totals = [[0 for _ in range(self.dim_l3)] for _ in range(self.dim_l3)]
        counts = [[0 for _ in range(self.dim_l3)] for _ in range(self.dim_l3)]
        for start, end in zip(starts, ends):
            target = self._compress_residual_to_l3(self._trajectory_residual(start, end))
            for i in range(self.dim_l3):
                for j in range(self.dim_l3):
                    if i == j:
                        continue
                    totals[i][j] += q_cos_lut(q_mod(target[j] - target[i], self.modulus), self.modulus)
                    counts[i][j] += 1
        rows: list[tuple[int, ...]] = []
        for i in range(self.dim_l3):
            row: list[int] = []
            for j in range(self.dim_l3):
                if i == j or counts[i][j] == 0:
                    row.append(0)
                else:
                    value = totals[i][j] // counts[i][j]
                    row.append(max(-COS_SCALE, min(COS_SCALE, value)))
            rows.append(tuple(row))
        return L3CouplingMatrix(tuple(rows), self.dim_l3, self.modulus)

    def build_l3_deductive_engine(
        self,
        l2_starts_q16: Iterable[Iterable[int]] | None = None,
        l2_ends_q16: Iterable[Iterable[int]] | None = None,
        *,
        relaxation_steps: int = 3,
        eta_bp: int = 1500,
    ) -> L3DeductiveEngine:
        """Build a runtime L3 deduction engine from consolidated sleep artifacts."""
        if l2_starts_q16 is None or l2_ends_q16 is None:
            matrix = L3CouplingMatrix.zero(self.dim_l3, self.modulus)
        else:
            matrix = self.derive_l3_coupling_matrix(l2_starts_q16, l2_ends_q16)
        return L3DeductiveEngine(
            dimension=self.dim_l3,
            modulus=self.modulus,
            relaxation_steps=relaxation_steps,
            eta_bp=eta_bp,
            initial_state=self.l3_state_q16,
            coupling_matrix=matrix,
        )

    def query_rule_q16(self, l2_start_q16: Iterable[int]) -> tuple[int, ...]:
        start = self._require_vector(l2_start_q16, self.dim_l2, "l2_start_q16")
        return self._predict_end(start)


@dataclass(frozen=True)
class L3SemanticState:
    """Immutable Q256 semantic-cortex state for L3 rule dynamics."""

    phases: tuple[int, ...]
    modulus: int = DEFAULT_MODULUS

    def __post_init__(self) -> None:
        normalized = q_vector(self.phases, self.modulus)
        if not normalized:
            raise LearningError("L3 semantic state must not be empty")
        object.__setattr__(self, "phases", normalized)

    @classmethod
    def zero(cls, dimension: int, modulus: int = DEFAULT_MODULUS) -> "L3SemanticState":
        if int(dimension) <= 0:
            raise LearningError("L3 semantic dimension must be positive")
        return cls(tuple(0 for _ in range(int(dimension))), modulus)

    @property
    def dimension(self) -> int:
        return len(self.phases)


@dataclass(frozen=True)
class L3CouplingMatrix:
    """Quantized phase-coupling matrix for integer Kuramoto-style L3 deduction.

    ``weights[i][j]`` is a signed Q15 value in ``[-COS_SCALE, COS_SCALE]``.
    The matrix does not authorize answers.  It is a runtime-ready artifact of
    offline sleep consolidation and still must be used behind proof/evidence
    gates when converted into user-visible claims.
    """

    weights: tuple[tuple[int, ...], ...]
    dimension: int
    modulus: int = DEFAULT_MODULUS

    def __post_init__(self) -> None:
        if int(self.dimension) <= 0:
            raise LearningError("L3 coupling dimension must be positive")
        if len(self.weights) != self.dimension:
            raise LearningError("L3 coupling row count mismatch")
        normalized_rows: list[tuple[int, ...]] = []
        for row in self.weights:
            if len(row) != self.dimension:
                raise LearningError("L3 coupling column count mismatch")
            clean_row: list[int] = []
            for value in row:
                weight = int(value)
                if weight < -COS_SCALE or weight > COS_SCALE:
                    raise LearningError("L3 coupling weights must be Q15 bounded")
                clean_row.append(weight)
            normalized_rows.append(tuple(clean_row))
        object.__setattr__(self, "weights", tuple(normalized_rows))

    @classmethod
    def zero(cls, dimension: int, modulus: int = DEFAULT_MODULUS) -> "L3CouplingMatrix":
        if int(dimension) <= 0:
            raise LearningError("L3 coupling dimension must be positive")
        return cls(tuple(tuple(0 for _ in range(int(dimension))) for _ in range(int(dimension))), int(dimension), modulus)


@dataclass(frozen=True)
class L3DeductionReport:
    """Bounded diagnostic report for one L3 phase-relaxation run."""

    before_state: tuple[int, ...]
    after_state: tuple[int, ...]
    steps: int
    before_sparsity_bp: int
    after_sparsity_bp: int
    mean_phase_motion: int
    max_phase_motion: int
    answer_authorized: bool = False
    reason: str = "L3 deduction is semantic relaxation only; proof gate still required"

    def __post_init__(self) -> None:
        if self.answer_authorized:
            raise LearningError("L3 deduction report cannot authorize answers")
        if self.steps <= 0:
            raise LearningError("L3 deduction report steps must be positive")


class L3DeductiveEngine:
    """Integer-only semantic L3 phase-relaxation engine.

    Runtime recurrence, over ``T_N^d`` with ``N = 2**256`` by default:

        h_i(t+1) = h_i(t) + eta * sum_j W_ij * sin_N(h_j - h_i) mod N

    ``sin_N`` is the LUT-backed integer sine from ``kernel.q16``.  All coupling
    weights are signed Q15 integers.  No PyTorch, NumPy or float constants are
    used in this runtime path.
    """

    def __init__(
        self,
        *,
        dimension: int = 16,
        modulus: int = DEFAULT_MODULUS,
        relaxation_steps: int = 3,
        eta_bp: int = 1500,
        initial_state: Iterable[int] | None = None,
        coupling_matrix: L3CouplingMatrix | None = None,
    ) -> None:
        if int(dimension) <= 0:
            raise LearningError("L3 dimension must be positive")
        if int(relaxation_steps) <= 0:
            raise LearningError("L3 relaxation_steps must be positive")
        if not 0 <= int(eta_bp) <= 10000:
            raise LearningError("eta_bp must be in [0, 10000]")
        self.dimension = int(dimension)
        self.modulus = int(modulus)
        self.relaxation_steps = int(relaxation_steps)
        self.eta_bp = int(eta_bp)
        self.state = L3SemanticState.zero(self.dimension, self.modulus) if initial_state is None else L3SemanticState(tuple(initial_state), self.modulus)
        if self.state.dimension != self.dimension:
            raise LearningError("initial L3 state dimension mismatch")
        self.coupling_matrix = coupling_matrix or L3CouplingMatrix.zero(self.dimension, self.modulus)
        if self.coupling_matrix.dimension != self.dimension:
            raise LearningError("initial coupling matrix dimension mismatch")

    def set_state(self, phases: Iterable[int]) -> None:
        state = L3SemanticState(tuple(phases), self.modulus)
        if state.dimension != self.dimension:
            raise LearningError("L3 state dimension mismatch")
        self.state = state

    def load_coupling_weights(self, weights_q15: Iterable[Iterable[int]]) -> None:
        weights = tuple(tuple(int(value) for value in row) for row in weights_q15)
        self.coupling_matrix = L3CouplingMatrix(weights, self.dimension, self.modulus)

    def load_coupling_matrix(self, matrix: L3CouplingMatrix) -> None:
        if matrix.dimension != self.dimension:
            raise LearningError("L3 coupling matrix dimension mismatch")
        self.coupling_matrix = matrix

    def _phase_step_from_q15(self, signed_q15: int) -> int:
        if signed_q15 == 0 or self.eta_bp == 0:
            return 0
        numerator = int(signed_q15) * self.eta_bp * (self.modulus // 2)
        denominator = COS_SCALE * 10000
        step = numerator // denominator
        if step == 0:
            return 1 if signed_q15 > 0 else -1
        return step

    def _relax_once(self, phases: tuple[int, ...]) -> tuple[int, ...]:
        weights = self.coupling_matrix.weights
        next_phases: list[int] = []
        for i, h_i in enumerate(phases):
            coupling_sum = 0
            for j, h_j in enumerate(phases):
                if i == j:
                    continue
                weight = weights[i][j]
                if weight == 0:
                    continue
                delta_phase = q_mod(h_j - h_i, self.modulus)
                sin_value = q_sin_lut(delta_phase, self.modulus)
                coupling_sum += (weight * sin_value) // COS_SCALE
            normalized = coupling_sum // max(1, self.dimension)
            next_phases.append(q_add(h_i, self._phase_step_from_q15(normalized), self.modulus))
        return tuple(next_phases)

    def relax(self, *, steps: int | None = None) -> L3SemanticState:
        count = self.relaxation_steps if steps is None else int(steps)
        if count <= 0:
            raise LearningError("L3 relaxation step count must be positive")
        phases = self.state.phases
        for _ in range(count):
            phases = self._relax_once(phases)
        self.state = L3SemanticState(phases, self.modulus)
        return self.state

    def relax_with_report(self, *, steps: int | None = None) -> L3DeductionReport:
        before = self.state.phases
        before_sparse = self.get_sparsity_score()
        after = self.relax(steps=steps).phases
        after_sparse = self.get_sparsity_score()
        motions = tuple(q_delta(a, b, self.modulus) for a, b in zip(before, after))
        return L3DeductionReport(
            before_state=before,
            after_state=after,
            steps=self.relaxation_steps if steps is None else int(steps),
            before_sparsity_bp=before_sparse,
            after_sparsity_bp=after_sparse,
            mean_phase_motion=sum(motions) // len(motions),
            max_phase_motion=max(motions),
        )

    def get_sparsity_score(self) -> int:
        total = sum(abs(q_sin_lut(phase, self.modulus)) for phase in self.state.phases)
        average_q15 = total // self.dimension
        return (average_q15 * 10000) // COS_SCALE

    def distance_to_state(self, target: Iterable[int]) -> int:
        target_state = L3SemanticState(tuple(target), self.modulus)
        if target_state.dimension != self.dimension:
            raise LearningError("target L3 state dimension mismatch")
        return q_toroidal_loss_vector(self.state.phases, target_state.phases, self.modulus)


__all__ = [
    "ConsolidationReport",
    "EpisodeFact",
    "EpisodeFactStatus",
    "EpisodeRecord",
    "L3CouplingMatrix",
    "L3DeductionReport",
    "L3DeductiveEngine",
    "L3SemanticState",
    "LearningError",
    "NoRegressionProbe",
    "RuleCandidate",
    "RuleStatus",
    "SleepConsolidator",
    "ToroidalSleepCompressionReport",
    "ToroidalSleepConsolidator",
]
